Sde
inform-health-informatics/Inform-DB pull request #112
Opened 2022-05-20 17:27 UTC by jeremyestein

## Reason for changes and summary
Emap-Star tables necessary for bringing in Smart Data Elements.

## Checklist for submitter & reviewer

- [ ] copy constructor copies the primary key Id of the entity
- [ ] copy constructor copies all other fields of the entity, starting with `super(other)`
- [ ] unique constraints added if appropriate
- [ ] text definition added to columns which could have more than 255 characters
- [ ] foreign key names are in the form `<entityClass>Id`, and no typos
- [ ] during run, glowroot is checked for query speed and indexes added if needed
- [ ] validation run completed and validated

2022-05-23 07:09 UTC, t-young31 commented on inform-db/src/main/java/uk/ac/ucl/rits/inform/informdb/smart_data_elements/SmartDataElementDefinition.java
> +     * \brief String description of a Smart Data Element, where available
Same docstring as `smartDataElementDescription` ?

2022-05-23 07:09 UTC, t-young31 commented on inform-db/src/main/java/uk/ac/ucl/rits/inform/informdb/smart_data_elements/SmartDataElement.java
> +        return null;
Why can't these be copied? Or this this `//TODO` ?

2022-05-23 14:59 UTC, jeremyestein commented on inform-db/src/main/java/uk/ac/ucl/rits/inform/informdb/smart_data_elements/SmartDataElement.java
> +        return null;
Yes, I was just drafting this, will be done in future.

2022-07-19 14:01 UTC, stefpiatek commented on inform-db/src/main/java/uk/ac/ucl/rits/inform/informdb/forms/Form.java
> +
I would remove this, if we do find that we have labs then we can add it in later on

2022-07-19 14:03 UTC, stefpiatek commented on inform-db/src/main/java/uk/ac/ucl/rits/inform/informdb/forms/Form.java
> +     * This may be redundant given valid from?
I think most users don't touch validFrom and storedFrom, so if we think it'd be useful for them to know the time of it being filled in, then we should have this. Assuming we get updates, will this update with the rest of the data?

2022-07-19 14:04 UTC, stefpiatek commented on inform-db/src/main/java/uk/ac/ucl/rits/inform/informdb/forms/Form.java
> +    private String formFilingUserId;
We don't model any clinical staff in star at the moment, is this usable or requested by users?

2022-07-19 14:05 UTC, stefpiatek commented on inform-db/src/main/java/uk/ac/ucl/rits/inform/informdb/forms/FormAnswer.java
> + * Stores the value assigned to a particular instance of an answered form question.
`\brief` here too please, and all the other classes too!

2022-07-19 14:11 UTC, stefpiatek commented on inform-db/src/main/java/uk/ac/ucl/rits/inform/informdb/forms/FormAnswerType.java
> +}
interchange, though I think we should probably only have a subset that we're expecting to parse. So drop things like database, hierarchy etc.

2022-07-19 14:12 UTC, stefpiatek commented on inform-db/src/main/java/uk/ac/ucl/rits/inform/informdb/forms/FormAnswer.java
> +    private Double valueAsNumber;
we've previously used real
```suggestion
    private Double valueAsReal;
```

2022-07-19 14:13 UTC, stefpiatek commented on inform-db/src/main/java/uk/ac/ucl/rits/inform/informdb/forms/FormAnswer.java
> +    private String valueAsString;
To match what we've previously used in other data types
```suggestion
    private String valueAsText;
```

2022-07-19 14:13 UTC, stefpiatek commented on inform-db/src/main/java/uk/ac/ucl/rits/inform/informdb/forms/FormAnswer.java
> +    private String formAnswerSourceId;
we've previously called this`internalId` so should try and keep our consistency there

2022-07-19 14:15 UTC, stefpiatek commented on inform-db/src/main/java/uk/ac/ucl/rits/inform/informdb/forms/FormAnswer.java
> +    private Instant valueAsUtcDatetime;
we are storing it with a timezone though, so would go with `valueAsDatetime`

2022-07-19 14:16 UTC, stefpiatek commented on inform-db/src/main/java/uk/ac/ucl/rits/inform/informdb/forms/FormDefinition.java
> +    private String formSourceId;
we've previously used `internalId` so should keep to that

2022-07-19 14:17 UTC, stefpiatek commented on inform-db/src/main/java/uk/ac/ucl/rits/inform/informdb/forms/FormDefinition.java
> +    private List<FormDefinitionFormQuestion> questions = new ArrayList<>();
I'm assuming that we use this somewhere?

2022-07-19 14:18 UTC, stefpiatek commented on inform-db/src/main/java/uk/ac/ucl/rits/inform/informdb/forms/FormDefinitionFormQuestion.java
> +        formDefinition.getQuestions().add(formDefinitionFormQuestion);
would be nicer to have an add question method on the formDefinition

2022-07-19 14:19 UTC, stefpiatek commented on inform-db/src/main/java/uk/ac/ucl/rits/inform/informdb/forms/FormQuestion.java
> +    private String formQuestionSourceId;
`internalId`

2022-07-19 14:20 UTC, stefpiatek commented on inform-db/src/main/java/uk/ac/ucl/rits/inform/informdb/forms/FormQuestion.java
> +    private String formQuestionConceptName;
there's a lot of prefixing with the table name, worth removing the prefix as it doesn't give us more information - and the same for other fields in this and other classes
```suggestion
    private String conceptName;
```

2022-07-19 14:21 UTC, stefpiatek commented on inform-db/src/main/java/uk/ac/ucl/rits/inform/informdb/forms/FormQuestion.java
> +     * Do we store this same value (an instance of ZC_DATA_TYPE) anywhere else in Star?
nope we dont currently

2022-07-19 14:22 UTC, stefpiatek commented on inform-db/src/main/java/uk/ac/ucl/rits/inform/informdb/forms/FormQuestion.java
> +     * (Convert to enum if we can be sure of possible values?)
I think we'd only want an enum if we changed processing based on it. otherwise we're just tying ourselves to not being able to accept new values if they add them

2022-07-19 14:24 UTC, stefpiatek commented on inform-db/src/main/java/uk/ac/ucl/rits/inform/informdb/forms/FormQuestion.java
> +     * Warning: Unknown if this is the same for every instance of the same SDE.
I'd imagine that they are specific to the type. Though I also would have thought that you'd have the "type" of SDE in the FormDefinition?

2022-07-20 11:39 UTC, jeremyestein commented on inform-db/src/main/java/uk/ac/ucl/rits/inform/informdb/forms/Form.java
> +     * This may be redundant given valid from?
Ok, fair enough. What happens with updates/deletes is one of the questions I've sent to Sarah to be passed on. Assuming it's possible to update a single answer within a form, the form filing timestamp would stay the same (since it's attached to the form) and the valid from for the answer would be the new time - so I think I've answered my own question there: we need two separate columns and `formFilingDatetime` should be renamed `formOriginalFilingDatetime` or at least documented so it's clear.

2022-07-20 11:40 UTC, jeremyestein commented on inform-db/src/main/java/uk/ac/ucl/rits/inform/informdb/forms/Form.java
> +    private String formFilingUserId;
No one requested it, I just put my finger in the air and added it :)
In that case I should probably delete it.

2022-07-21 14:30 UTC, jeremyestein commented
Should be all fixed. Now working on core processing.

2022-08-01 07:23 UTC, t-young31 approved these changes
Looks great 🎉

2022-08-01 07:23 UTC, t-young31 commented on inform-db/src/main/java/uk/ac/ucl/rits/inform/informdb/forms/Form.java
> +        formAnswer.setFormId(this);
Would you mind explaining what happens here? 
Does a new id gets generated for this instance, if so what happens to the old one?

2022-08-01 07:23 UTC, t-young31 commented on inform-db/src/main/java/uk/ac/ucl/rits/inform/informdb/forms/Form.java
> +    public Form() {}
Should the minimal constructor have `mrn` and `visit` arguments? Feels less likely that you'd then try and persist something that didn't meet the constraints. 
I guess neither is the ideal solution when at least one needs to be not null 😕

2022-08-01 07:23 UTC, t-young31 commented on inform-db/src/main/java/uk/ac/ucl/rits/inform/informdb/forms/Form.java
> +    private Long formId;
Missing a `\brief`

2022-08-01 07:23 UTC, t-young31 commented on inform-db/src/main/java/uk/ac/ucl/rits/inform/informdb/forms/FormAnswer.java
> +    public FormAnswer() {
If this only has a default constructor are all the fields nullable? It feels like an answer is no use without at least the question it relates to(?)

2022-08-01 07:23 UTC, t-young31 commented on inform-db/src/main/java/uk/ac/ucl/rits/inform/informdb/forms/FormDefinition.java
> +     *
```suggestion
```

2022-08-01 07:23 UTC, t-young31 commented on inform-db/src/main/java/uk/ac/ucl/rits/inform/informdb/forms/FormDefinitionFormQuestion.java
> +    public FormDefinitionFormQuestion() {
Could be private?

2022-08-01 07:23 UTC, t-young31 commented on inform-db/src/main/java/uk/ac/ucl/rits/inform/informdb/forms/FormQuestion.java
> +    public FormQuestion() {
(similar to above) should probably require constructing on `internalId` if it's not nullable?

2022-08-01 08:21 UTC, stefpiatek commented on inform-db/src/main/java/uk/ac/ucl/rits/inform/informdb/forms/Form.java
> +    @OneToMany(mappedBy = "formId", fetch = FetchType.EAGER, cascade = CascadeType.ALL)
should have spotted it earlier, but do we want a cascade here? Generally if we're deleting then we want to make sure that we've audited and deleted everything manually

2022-08-01 09:10 UTC, stefpiatek commented
In the spirit of trying to get open PR time down - would you have some time early this week to address the requested changes @jeremyestein?

2022-08-05 18:35 UTC, jeremyestein commented on inform-db/src/main/java/uk/ac/ucl/rits/inform/informdb/forms/Form.java
> +        formAnswer.setFormId(this);
Have added a comment, here for reference:
```
    /**
     * Add the given FormAnswer to this instance of a Form.
     * @param formAnswer the formAnswer to add
     */
```
I'm making links in both directions so that Hibernate can find the relationship easily. I think you can sometimes get away with only doing it one way round (depending on which is "owning" side?), but I'd rather not remember that and just do it both ways.
As far as I know, nothing happens to IDs that wouldn't have happened anyway. A possible source of confusion is the field naming convention we use that always includes the suffix "Id" - `setFormId` is actually setting a field of type `Form`, so it's a Java object reference and the field which maps to the DB PK may or may not have been set yet but it doesn't make any difference.

2022-08-05 18:38 UTC, jeremyestein commented on inform-db/src/main/java/uk/ac/ucl/rits/inform/informdb/forms/Form.java
> +    public Form() {}
I'm hoping that we will always know `visit` and that can just be a simple non-nullable field, and we can lose that constraint. As for constructors you're probably right.

2022-08-15 12:22 UTC, skeating requested changes
issues need addressing

2022-09-05 14:21 UTC, jeremyestein commented on inform-db/src/main/java/uk/ac/ucl/rits/inform/informdb/forms/FormDefinitionFormQuestion.java
> +    public FormDefinitionFormQuestion() {
No, AFAICT JPA requires a no-arg public or protected constructor in Entity classes.

2022-09-05 15:10 UTC, jeremyestein commented on inform-db/src/main/java/uk/ac/ucl/rits/inform/informdb/forms/FormDefinitionFormQuestion.java
> +    public FormDefinitionFormQuestion() {
In fact `TestCopyConstructor` uses it too.

2022-09-05 15:22 UTC, jeremyestein commented on inform-db/src/main/java/uk/ac/ucl/rits/inform/informdb/forms/FormQuestion.java
> +    public FormQuestion() {
I've tightened up all the constructors so they make a slightly more useful object. Unfortunately the no-arg constructors are needed by `TestCopyConstructor`.

2022-09-05 17:06 UTC, jeremyestein commented on inform-db/src/main/java/uk/ac/ucl/rits/inform/informdb/forms/Form.java
> +    @OneToMany(mappedBy = "formId", fetch = FetchType.EAGER, cascade = CascadeType.ALL)
I put these in because I was having trouble getting everything to save in the right order, but I agree it's not great. I'm going to try and re-order stuff to make it work without cascade.

2022-09-13 14:50 UTC, jeremyestein commented on inform-db/src/main/java/uk/ac/ucl/rits/inform/informdb/forms/Form.java
> +    @OneToMany(mappedBy = "formId", fetch = FetchType.EAGER, cascade = CascadeType.ALL)
Have removed all cascades in form tables.

2022-09-21 08:40 UTC, stefpiatek approved these changes
Just had a look over outstanding comments, a couple of blocking changes but looking good

2022-09-21 08:40 UTC, stefpiatek commented on inform-db/src/main/java/uk/ac/ucl/rits/inform/informdb/forms/Form.java
> +    public Form() {}
not blocking but I think this still stands

2022-09-21 08:40 UTC, stefpiatek commented on inform-db/src/main/java/uk/ac/ucl/rits/inform/informdb/forms/FormAnswer.java
> +    private String valueAsString;
This doesn't look like it's changed, and is a blocking change

2022-09-21 08:40 UTC, stefpiatek commented on inform-db/src/main/java/uk/ac/ucl/rits/inform/informdb/forms/FormAnswer.java
> +    private Instant valueAsUtcDatetime;
also this (blocking)

2022-09-21 15:15 UTC, jeremyestein commented on inform-db/src/main/java/uk/ac/ucl/rits/inform/informdb/forms/Form.java
> +    public Form() {}
I added another constructor that takes `TemporalFrom` and `FormDefinition`, but some tests fail if the no-arg constructor is completely removed (just the cascading delete tests, I haven't looked into why).
Re `mrn` and `visit`, I need to go and double check this but I think some SDEs are attached to MRNs only, so `visit` does actually need to be null sometimes. When `visit` is known, do we also want `mrn` to be filled in? Our schema doesn't seem to be consistent on this: advance decisions and patient conditions point to both, but consult requests only point to visits. Do we support moving a visit from one MRN to another?

2022-09-22 09:39 UTC, stefpiatek approved these changes
Thanks for getting this in, some queries about constraints that are all non-blocking

2022-09-22 09:39 UTC, stefpiatek commented on inform-db/src/main/java/uk/ac/ucl/rits/inform/informdb/forms/FormQuestion.java
> +    private String conceptName;
can this ever be null?

2022-09-22 09:39 UTC, stefpiatek commented on inform-db/src/main/java/uk/ac/ucl/rits/inform/informdb/forms/FormQuestion.java
> +    private String conceptAbbrevName;
can this ever be null?

2022-09-22 09:39 UTC, stefpiatek commented on inform-db/src/main/java/uk/ac/ucl/rits/inform/informdb/forms/FormAnswer.java
> +    private String internalId;
can this ever be null? and should be it unique?

2022-09-22 09:39 UTC, stefpiatek commented on inform-db/src/main/java/uk/ac/ucl/rits/inform/informdb/forms/FormAnswer.java
> +    private String context;
can this ever be null?

2022-09-22 09:39 UTC, stefpiatek commented on inform-db/src/main/java/uk/ac/ucl/rits/inform/informdb/forms/FormDefinition.java
> +    private String name;
can this ever be null?

2022-09-22 11:24 UTC, jeremyestein commented on inform-db/src/main/java/uk/ac/ucl/rits/inform/informdb/forms/FormQuestion.java
> +    private String conceptAbbrevName;
Yes, they don't all have abbreviated names

2022-09-22 11:31 UTC, jeremyestein commented on inform-db/src/main/java/uk/ac/ucl/rits/inform/informdb/forms/FormAnswer.java
> +    private String context;
Yes it can, In 137 cases out of ~30 million :/

2022-09-26 11:47 UTC, skeating approved these changes

2022-10-03 13:55 UTC, merged