Index tables
inform-health-informatics/Inform-DB pull request #35
Opened 2020-11-13 10:31 UTC by stefpiatek

Add slow indexes, might be a bit overkill on the location visits but this was from the slow queries.

2020-11-16 13:43 UTC, klapaukh requested changes

2020-11-16 13:43 UTC, klapaukh commented on inform-db/src/main/java/uk/ac/ucl/rits/inform/informdb/movement/LocationVisit.java
> +        @Index(name = "location_visit_discharge_time", columnList = "locationId, hospitalVisitId, dischargeTime DESC")})
So these indexes seem like overkill maybe? Maybe we just need a "is null discharge time" index or something for now? That's just a guess. These may be exactly what is needed. What is their use case?

2020-11-16 13:43 UTC, klapaukh commented on inform-db/src/main/java/uk/ac/ucl/rits/inform/informdb/movement/LocationVisit.java
> +    @Column(columnDefinition = "timestamp with time zone", nullable = false)
If you create a location visit from a mid stream A08 it won't have an admission time will it?

2020-11-16 15:23 UTC, stefpiatek commented on inform-db/src/main/java/uk/ac/ucl/rits/inform/informdb/movement/LocationVisit.java
> +        @Index(name = "location_visit_discharge_time", columnList = "locationId, hospitalVisitId, dischargeTime DESC")})
yeah that's fair. there are two selects that use either `hospitalVisitId = ? AND dischargeDateTime IS NULL` and `locationVisitId = ?, hospitalVisitId = ? AND dischargeDateTime IS NULL` so yeah I think a null discharge time. I assume that null makes it particularily slow in a query, or is it work indexing the hospitalVisitId as well?

2020-11-16 15:28 UTC, stefpiatek commented on inform-db/src/main/java/uk/ac/ucl/rits/inform/informdb/movement/LocationVisit.java
> +    @Column(columnDefinition = "timestamp with time zone", nullable = false)
Ah yes, that's a good point, I'll revert that change

2020-11-16 15:55 UTC, stefpiatek commented on inform-db/src/main/java/uk/ac/ucl/rits/inform/informdb/movement/LocationVisit.java
> +        @Index(name = "location_visit_discharge_time", columnList = "locationId, hospitalVisitId, dischargeTime DESC")})
Is there a clean way to add a partial index for is null in hibernate, or is this a point where we should be using liquibase?

2020-11-18 10:43 UTC, klapaukh commented on inform-db/src/main/java/uk/ac/ucl/rits/inform/informdb/movement/LocationVisit.java
> +        @Index(name = "location_visit_discharge_time", columnList = "locationId, hospitalVisitId, dischargeTime DESC")})
So you don't need to have an index over all the conditions. It's ok to still have a linear search bit as long as that part is small. Ideally we shouldn't have any composite keys unless single column ones don't work I think.

2020-11-18 10:49 UTC, stefpiatek commented on inform-db/src/main/java/uk/ac/ucl/rits/inform/informdb/movement/LocationVisit.java
> +        @Index(name = "location_visit_discharge_time", columnList = "locationId, hospitalVisitId, dischargeTime DESC")})
okay, so I'll creata an index for the hospitalVisit and locationId and see where that gets us

2020-11-20 16:54 UTC, klapaukh approved these changes

2020-11-20 17:08 UTC, merged