Consults
inform-health-informatics/Inform-DB pull request #58
Opened 2021-06-20 17:07 UTC by AnikaC-git

Adding in processing for consultation requests with respective test cases as outline by @stefpiatek.

2021-06-21 09:59 UTC, stefpiatek requested changes
I don't think that this is the most recent version, I'm expecting a ConsultationRequestQuestion class here. When do do get there I'd be tempted to rename it ConsultationQuestion potentially

2021-06-21 09:59 UTC, stefpiatek commented on inform-db/src/main/java/uk/ac/ucl/rits/inform/informdb/consults/ConsultationRequest.java
> +import java.util.HashMap;
getting a fair few checkstyle errors here. Interestingly the CI hasn't failed so we should probably change that too, i guess editing the .travis.yml to run checkstyle, adding in a line with `mvn checkstyle:check `

2021-06-21 09:59 UTC, stefpiatek commented on inform-db/src/main/java/uk/ac/ucl/rits/inform/informdb/consults/ConsultationRequestType.java
> +public class ConsultationRequestType extends TemporalCore<ConsultationRequestType, ConsultationRequestTypeAudit> {
maybe just ConsultationType?

2021-06-21 09:59 UTC, stefpiatek commented on inform-db/src/main/java/uk/ac/ucl/rits/inform/informdb/consults/ConsultationRequest.java
> +//    private boolean cancelled;
should be deleted rather than commented out, but maybe in the most recent version it is?

2021-06-21 10:17 UTC, AnikaC-git commented
> I don't think that this is the most recent version, I'm expecting a ConsultationRequestQuestion class here. When do do get there I'd be tempted to rename it ConsultationQuestion potentially

@stefpiatek, sorry, it seems that one still has to push one's changes ... latest sources should be there now but not touched after review. Will move on to that shortly.

2021-06-21 10:22 UTC, stefpiatek commented on inform-db/src/main/java/uk/ac/ucl/rits/inform/informdb/consults/ConsultationRequest.java
> +    private ConsultationRequestType consultationRequestTypeId;
Oh i'd also use the same column name and field name here too

2021-06-21 10:25 UTC, stefpiatek reviewed
Looks good, added in a couple of comments for the other files

2021-06-21 10:25 UTC, stefpiatek commented on inform-db/src/main/java/uk/ac/ucl/rits/inform/informdb/consults/ConsultationRequest.java
> +    private String consultId;
the consult Id should be required

2021-06-21 10:25 UTC, stefpiatek commented on inform-db/src/main/java/uk/ac/ucl/rits/inform/informdb/consults/ConsultationRequestQuestion.java
> +//        @Index(name = "lsq_question_id", columnList = "questionId")})
should be deleted

2021-06-21 11:00 UTC, AnikaC-git commented on inform-db/src/main/java/uk/ac/ucl/rits/inform/informdb/consults/ConsultationRequest.java
> +import java.util.HashMap;
I am not sure that I follow this comment. I did run the style checker manually and got that no problems were found. That was with the latest version of the file that is pushed to the repo now. Is that something else though that you are referring to here?

2021-06-21 11:12 UTC, AnikaC-git commented on inform-db/src/main/java/uk/ac/ucl/rits/inform/informdb/consults/ConsultationRequestType.java
> +public class ConsultationRequestType extends TemporalCore<ConsultationRequestType, ConsultationRequestTypeAudit> {
Renamed accordingly

2021-06-21 11:26 UTC, AnikaC-git commented on inform-db/src/main/java/uk/ac/ucl/rits/inform/informdb/consults/ConsultationRequest.java
> +//    private boolean cancelled;
Yes, that was due to looking at an older version. I did double-check now and is removed.

2021-06-21 11:28 UTC, AnikaC-git commented on inform-db/src/main/java/uk/ac/ucl/rits/inform/informdb/consults/ConsultationRequest.java
> +    private ConsultationRequestType consultationRequestTypeId;
Did that when renaming  ;)

2021-06-21 12:34 UTC, AnikaC-git commented on inform-db/src/main/java/uk/ac/ucl/rits/inform/informdb/consults/ConsultationRequestQuestion.java
> +//        @Index(name = "lsq_question_id", columnList = "questionId")})
Oopsie ... done now.

2021-06-21 12:35 UTC, AnikaC-git commented on inform-db/src/main/java/uk/ac/ucl/rits/inform/informdb/consults/ConsultationRequest.java
> +    private String consultId;
Where does this ID come from in the ConsultRequest message assuming that then would need to be set by minimal constructor too? Is that the msg.getSourceMessageId()?

2021-06-21 13:20 UTC, stefpiatek commented on inform-db/src/main/java/uk/ac/ucl/rits/inform/informdb/consults/ConsultationRequest.java
> +    private String consultId;
It's the epicConsultId (the source message ID would be the unid from the IDS so we know which message it was generated from). Yep worth adding it to the minimal constructor. You could add a unique constraint on that column and just query by that as well really, not sure if there's benefit for querying by all the other fields because as far as I know the consult Id is unique

2021-06-21 13:22 UTC, stefpiatek commented on inform-db/src/main/java/uk/ac/ucl/rits/inform/informdb/consults/ConsultationRequest.java
> +    private Mrn mrnId;
Oh actually we should just remove the MRN here, it's linked through the hospital visit and consults are linked to the visit

2021-06-21 13:23 UTC, stefpiatek commented on inform-db/src/main/java/uk/ac/ucl/rits/inform/informdb/consults/ConsultationRequest.java
> +        this.hospitalVisitId = other.hospitalVisitId;
this should be a complete copy, so should copy optional fields

2021-06-21 13:59 UTC, AnikaC-git commented on inform-db/src/main/java/uk/ac/ucl/rits/inform/informdb/consults/ConsultationRequest.java
> +        this.hospitalVisitId = other.hospitalVisitId;
Added in additional fields

2021-06-21 14:03 UTC, AnikaC-git commented on inform-db/src/main/java/uk/ac/ucl/rits/inform/informdb/consults/ConsultationRequest.java
> +    private Mrn mrnId;
Sounds good, MRN removed

2021-06-21 14:09 UTC, AnikaC-git commented on inform-db/src/main/java/uk/ac/ucl/rits/inform/informdb/consults/ConsultationRequest.java
> +    private Mrn mrnId;
Sounds reasonable to me and removed it accordingly.

2021-06-21 16:55 UTC, AnikaC-git commented on inform-db/src/main/java/uk/ac/ucl/rits/inform/informdb/consults/ConsultationRequest.java
> +import java.util.HashMap;
I think I added now what you requested ...

2021-06-22 11:24 UTC, klapaukh approved these changes
It might be worth thinking about merging all the different questions together. or at least clearly deciding on why or why not to do that.

2021-06-22 11:24 UTC, klapaukh commented on .travis.yml
> +    - mvn -X checkstyle:check
`-X` is an unusual flag to include? Any reason for it?

2021-06-22 11:24 UTC, klapaukh commented on inform-db/src/main/java/uk/ac/ucl/rits/inform/informdb/consults/ConsultationRequest.java
> +    private Boolean closedDueToDischarge = false;
Is this (and cancelled) nullable? Or should it be non null?

2021-06-22 11:24 UTC, klapaukh commented on inform-db/src/main/java/uk/ac/ucl/rits/inform/informdb/consults/ConsultationRequestQuestion.java
> +public class ConsultationRequestQuestion extends
As in the other PR should this really be separate from labQuestions? Or should there be unified questions with answers?

2021-06-24 14:34 UTC, AnikaC-git commented on .travis.yml
> +    - mvn -X checkstyle:check
To have more output when looking in the browser error message. I couldn't get it to fail locally and at least wanted to address the problem for now. Turns out, I finally got it to fail locally and the flag is no longer needed. So will remove it accordingly.

2021-06-24 14:41 UTC, AnikaC-git commented on inform-db/src/main/java/uk/ac/ucl/rits/inform/informdb/consults/ConsultationRequest.java
> +    private Boolean closedDueToDischarge = false;
@stefpiatek -- I do not have data access yet, would you have thoughts on that?

2021-06-24 15:01 UTC, stefpiatek commented on inform-db/src/main/java/uk/ac/ucl/rits/inform/informdb/consults/ConsultationRequestQuestion.java
> +public class ConsultationRequestQuestion extends
yeah I think it'd be painful to get hibernate to be happy to have them as foreign keys with different class types, but if you've got an easy solution to it then that seems sensible

2021-06-24 15:14 UTC, stefpiatek approved these changes
Looks good, some small changes and I guess we could do with resolving Roma's questions as well

2021-06-24 15:14 UTC, stefpiatek commented on inform-db/src/main/java/uk/ac/ucl/rits/inform/informdb/consults/ConsultationRequest.java
> +    private Boolean closedDueToDischarge = false;
I think it should be default to false as we only set it to true if it's been closed by the automated discharge

2021-06-24 15:14 UTC, stefpiatek commented on inform-db/src/main/java/uk/ac/ucl/rits/inform/informdb/consults/ConsultationRequestQuestion.java
> +        TemporalCore<uk.ac.ucl.rits.inform.informdb.consults.ConsultationRequestQuestion, ConsultationRequestQuestionAudit> {
there's a couple of full references as `uk.ac.ucl.rits.inform.informdb.consults.ConsultationRequestQuestion`, which should be replaced to `ConsultationRequestQuestion`

2021-06-24 15:14 UTC, stefpiatek commented on inform-db/src/main/java/uk/ac/ucl/rits/inform/informdb/consults/ConsultationType.java
> +    private String standardisedCode;
I don't know if this is a standardised code (unless it is in a medical nomenclature like SNOMED, ICD-10 etc.), I would just call it code/type

2021-06-24 15:44 UTC, AnikaC-git commented on inform-db/src/main/java/uk/ac/ucl/rits/inform/informdb/consults/ConsultationRequest.java
> +    private Boolean closedDueToDischarge = false;
Thanks for clarifying, much appreciated!

2021-06-24 16:29 UTC, AnikaC-git commented on inform-db/src/main/java/uk/ac/ucl/rits/inform/informdb/consults/ConsultationRequestQuestion.java
> +        TemporalCore<uk.ac.ucl.rits.inform.informdb.consults.ConsultationRequestQuestion, ConsultationRequestQuestionAudit> {
Not sure how they got in, but removed now ...

2021-06-24 16:31 UTC, AnikaC-git commented on inform-db/src/main/java/uk/ac/ucl/rits/inform/informdb/consults/ConsultationType.java
> +    private String standardisedCode;
changed accordingly

2021-06-25 08:16 UTC, stefpiatek approved these changes
delightful, should have a think about the questions and answers

2021-07-05 15:10 UTC, AnikaC-git commented on inform-db/src/main/java/uk/ac/ucl/rits/inform/informdb/consults/ConsultationRequestQuestion.java
> +public class ConsultationRequestQuestion extends
Decided to make this into separate issue as fix. Tables will be merged into one question-answer table going forward.

2021-07-05 15:11 UTC, merged

2021-07-05 15:59 UTC, stefpiatek commented
fine for inform-db, but for all other repos should do the merges at the same time so that develop can always be deployed. I'd also do the merging after a validation run