Update dependencies
inform-health-informatics/Inform-DB pull request #89
Opened 2022-02-04 14:57 UTC by stefpiatek

Oopf sorry about the whitespace

2022-02-04 17:12 UTC, skeating requested changes

2022-02-04 17:12 UTC, skeating commented on inform-annotations/pom.xml
> +      <version>${hibernate-core.version}</version>
defined  ?

2022-02-04 17:12 UTC, skeating commented on inform-db/pom.xml
> +      <version>${hibernate-core.version}</version>
defined ?

2022-02-04 17:12 UTC, skeating commented on inform-db/pom.xml
> +      <version>${junit-jupiter.version}</version>
?

2022-02-04 17:12 UTC, skeating commented on inform-db/pom.xml
> +      <groupId>org.junit.jupiter</groupId>
repeat

2022-02-04 17:22 UTC, stefpiatek commented on inform-annotations/pom.xml
> +      <version>${hibernate-core.version}</version>
sure is, but in the parent pom <repo>/pom.xml

2022-02-04 17:22 UTC, stefpiatek commented on inform-db/pom.xml
> +      <groupId>org.junit.jupiter</groupId>
sure is, but in the parent pom <repo>/pom.xml

2022-02-04 17:23 UTC, stefpiatek commented on inform-db/pom.xml
> +      <version>${junit-jupiter.version}</version>
sure is, but in the parent pom <repo>/pom.xml

2022-02-07 09:40 UTC, skeating approved these changes

2022-02-11 09:35 UTC, merged